Update READEM.md
MaKs-Tkachyk/infinite-image-slider pull request #8
Opened 2023-02-15 10:23 UTC by alex-dishen

2023-02-15 10:41 UTC, MaKs-Tkachyk approved these changes

2023-02-16 11:13 UTC, MaKs-Tkachyk approved these changes

2023-02-17 07:11 UTC, MaKs-Tkachyk approved these changes

2023-02-17 11:26 UTC, Lulca requested changes

2023-02-17 11:26 UTC, Lulca commented on README.md
> +## 👉 [Default](https://codesandbox.io/s/default-demo-g81knf) 👈
Remove  👉   👈 for all titles (to mutch)

2023-02-17 11:45 UTC, Lulca approved these changes

2023-02-17 11:45 UTC, merged